language: php

php:
  - 7.0
  - 5.6

install:
  - sudo apt-get update && sudo apt-get upgrade -y --autoremove
  - sudo apt-get install sqlite3

before_script: 
  - composer self-update
  - composer install