language: php

php:
  - 7.2
  - nightly
stages:
#  - name: deploy
#    if: branch = master
install:
  # Making sure we're on the latest
  - sudo apt-get update #&& sudo apt-get upgrade -y
  # We need sqlite3 to test with.
  - sudo apt-get install sqlite3

before_script:
  - composer require --dev php-coveralls/php-coveralls
  - composer install

#before_deploy:
deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis-CI Builder"
  - git config --local user.email "builds@travis-ci.org"
  - echo ${TRAVIS_TAG}
  #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  #- git tag $TRAVIS_TAG

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  on: 
#    tags: true

after_script:
  - php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v