language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
matrix:
#Temporarily allow failures on PHP nightly while coveralls.io catches up.
  allow_failures:
    - php: nightly

install:
  # Making sure we're on the latest
  - sudo apt-get update #&& sudo apt-get upgrade -y
  # We need sqlite3 to test with.
  - sudo apt-get install sqlite3

before_script:
  - composer install

after_script:
  - php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v