language: php

php:
  - 7.2
  - nightly

install:
  # Making sure we're on the latest
  - sudo apt-get update #&& sudo apt-get upgrade -y
  # We need sqlite3 to test with.
  - sudo apt-get install sqlite3

before_script: 
  - composer self-update
  - composer require --dev php-coveralls/php-coveralls
  - composer install

after_script:
  - php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v